//
//  HybridTests.swift
//  AgePonyCoreTests
//
//  Known-answer tests for the MLKEM768-X25519 post-quantum recipient
//  (age1pq / mlkem768x25519).
//
//  The vectors were generated by the filippo.io/hpke reference implementation —
//  the exact construction the `age` CLI v1.3.0+ uses — with a fixed identity seed,
//  fixed encapsulation randomness, and a fixed file key. They are the same vectors
//  the Android suite pins in HybridRecipientTests.kt, so passing here proves the
//  two AgePony implementations and standard age all agree byte for byte.
//

import XCTest
@testable import AgePonyCore

final class HybridTests: XCTestCase {

    private func hex(_ s: String) -> Data {
        var d = Data(); var i = s.startIndex
        while i < s.endIndex {
            let j = s.index(i, offsetBy: 2)
            d.append(UInt8(s[i..<j], radix: 16)!); i = j
        }
        return d
    }

    private func hexString(_ d: Data) -> String {
        d.map { String(format: "%02x", $0) }.joined()
    }

    /// Identity seed — the AGE-SECRET-KEY-PQ- payload.
    private var seed: Data { hex("000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f") }

    /// File key (16 bytes) and the 64-byte deterministic encapsulation randomness
    /// (ML-KEM `m` || X25519 ephemeral scalar).
    private var fileKey: Data { hex("404142434445464748494a4b4c4d4e4f") }
    private var testRandom: Data {
        hex("808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9f"
            + "a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf")
    }

    /// Expected 1216-byte hybrid public key derived from `seed`.
    private var expectedPublicKey: Data {
        hex(
            "6f54098a0a0e641146614b6960ba60d8603d62f447f9ab499b47bd6906cc40b0"
            + "61d8634a3e88906f284958e7441ca6c725cbb97095b7671a462b6681c9e6580b"
            + "bc8d60b149fa60261043afbba52f205a6028384851596adf371abea98d334738"
            + "3d2bb673438f6783612bf87014f7b91a89740265345df679340473d1c4c17688"
            + "6e5e29b8f058bb7c735316686cff5c3beb8c261cb00970a69c1afcc54b94cb86"
            + "e1ce63ba636e395ca45101e21c7bd04c313ea19af24141efd2ad44416a25ba4f"
            + "65910ef7d8809c3093f04aaf00e3cd96e35c4aa3c802c18ad6f39da4b4b8d98c"
            + "8bd7902d83a07ba45396674a60243cab93e80fd9b1c8777376a9cc0d6fa115e2"
            + "639380b9c6be7848bd13588c64703a0535d19a0f81633a976a0a105b66ee285d"
            + "0fd255e82c0331925f4383b6efc761ef6099235a0b98726358aa9d01b8b89651"
            + "9f921474bb7c14bb22252b5c2f10d41246c9b23e7644849367f541a15f63bc92"
            + "8a39bb7bc73f07b665c496bb6558c8f45489a72ec4bacd34e9c594c33871b723"
            + "f03495e88b4391ab26e43043deb6117b3919e45c4c1b16ab28e47ddd72366385"
            + "4766192fc1806ca70abb786cbdb30932e68c8a370bcfb07983a012c3266b93ef"
            + "a62657f4b838374cb0bb95e0ec06541b0765d99cf153bc6b96135ca780a55b36"
            + "47789e31915e46283cf9c7bb6e8453fb6682105141f1dc0d00d85eed703b6c6c"
            + "961f79c845276b4248949c06782e513eb2991b95d96042e38cbeda352449b2b5"
            + "084ebda5226a6206400789130a3096449848b629feea4a2c2a743c4a0ddc9cb3"
            + "f3d676fc563731b26c4a1a66dc8459170056d57697f1443b81a9a34412bb7bf0"
            + "5f3327575a5911dd301d6053867f3c3080711f1bf11587b0bb2984276b2685e7"
            + "756210e4b3f8955384231e558c6f510c91e0fc56b5d1885ff2949e95a46bc1be"
            + "e1fa71f5027e10c443b0e91d0fd7440f467a27221212e88f5c6ba64296cae0d2"
            + "07bfc60f88c7cfb5c45aa1839d18cb37c45843e5426a4a90c802b6428f953c35"
            + "9c4ac0603452fac0b7361e2fd35dcc885a92145d4fca0158f1b7d70b4bcd118e"
            + "4a2a4154438df310c44a9a1b99ea415907267a88b0624241579c1722f46ed61c"
            + "2e3eca545c9970517175399b800db25da39593d06490d7142c00e88d2db047e9"
            + "898bdb7acb7ed907f6e30416cc0de54a242c0a2126302f5d54c85bc66ac2f83c"
            + "797945b5067caa42bd2e0c19ca97506e507ab0a5c9f5633708499c19f24aec51"
            + "3bd3903a5d73b6ec4991f7c72eb991c1c37889805cb1ea38a0cc02176b27c58d"
            + "638ce5a32668457cf9b9be027ca0214057971725d54102e8996716eb2ad82345"
            + "3b605b855370b1b21b3932cded4160aa9973c7ebae5ac4764d94cf7cc9506f07"
            + "7bad73012dbb4ac8140a38746412eb33c9514596205f707635862217d9b60918"
            + "c6268d9344915b847a2476c1a270f154a5c84234165acfc869398702cea9e9a0"
            + "7e7b0e99ea9bdcb7841fe9c0fa25c8338092561a3edddc7001f478ad65781a60"
            + "24aad165d9b6979adac448a4462f564685527f762434fe9a425a84437b457392"
            + "eca80c913506151e3a13239f342fca7655b6eaae845a221ceb3e67f5639c6193"
            + "f6fdeef57e399b808b7f3aa2b5740aaded90163dc5d775c9faf7f1fbd075dab3"
            + "44e9d7d146647281fbba7b3c56cafd5833b7a930ec4206e7c3a6d7764fe81d7a"
        )
    }

    /// Expected 1120-byte encapsulation.
    private var expectedEnc: Data {
        hex(
            "9af7658f5c013bae036cdc68e1438eeb76c2759ce252c2828d1e474b9276ae94"
            + "4d621375a03271c0ef063511e426c567cc3c6476403472f7ad0ccdc49025017b"
            + "4ff3eefd7e3a85c4f9b76895ed363e0b9f55a2c0ae39e36595e77583d02dec60"
            + "a0c91bc1c8f644e82b996cc0cb71600cc1aa0c1fc20dee83a7c30cd3101ea354"
            + "b46f1e7168c01eca50f3c028ea5ad510ad35f70456f0688ed19deecbd6d5c6f8"
            + "718986e79e0e11ecebced1a2db7f6f3089420e05898cca2953a7377ffe374c3c"
            + "fb512cf88c601bf9547de954f8a47796d039e0715b72e7ddcc9190f59948be2d"
            + "94ad9a4ce338c2389fdb6bb7c59254ef7efc1d9812c2a50fd53a394660b21fee"
            + "65122fcb07d7397041e11a961603322e3f2817e82f9c810b7906ab5068e149e6"
            + "a90e53cedd715c223059bdeb2ba1cca732023ab6ebc816e1ae0dff23dfe4ed03"
            + "5efc284c6e3cef88e31182a33229bedd64b44e279f64bd949ca19ceef41107da"
            + "770067229c1b7790c0cb405643a3ae34a6a96aa26140603e2edfc148c69bff95"
            + "3c127f31ade1f05c759804b83d47017c85d9d7ca37b8009fd966be9fac554de5"
            + "251d4d9b80ab71b54219af91d1fbcb2f321c2b1c91e7c1d59d23c7b6818cecec"
            + "c246b44fa930d5f201b000b07e88470cf21f3f90a5fd6c5aacfdd91872b13392"
            + "572fddedcbfd305518a7ad9deb1460f31c56724652aa91722e988b43ffe81c7c"
            + "ba956600489789848dce49b6dc171e42bc5ddbc98f032643a35b287756b4aebe"
            + "e514d94c74d36f2af0e953278ace7fedf4830477980639a785774de16500a51b"
            + "7e0e2d1b6be35caaa83f1583683174256c3193178495d84d479f6b095d7c3842"
            + "32b566f950f8c19b26d888b5501e0670cb00b52f873ec217ed0a213cbc389bda"
            + "4def471398600c018c9443c3488a7f39246201acf5477974888e8b29e60cb469"
            + "f46111f0439e0dc282d990117d7d93dbd7583366ae4c67b09445cfd0ae069ff4"
            + "6743ebd74dfc2322c04405503cdc67b309b988e3b95496bc7b4d0b485ce40317"
            + "8cd11d133e11b08ad34f2e5a4527b315e9ca54e1bb717d9a3b140335f8b112c9"
            + "36c0195282d08c5e32a39566450da94310f29bbf19e04852ff85abd9016cde76"
            + "6df124dba7329ab248034bce5655c2e88de198e6aa82e6c57ba265dff0801262"
            + "abfbb20d25a5d56193cd4f75019a69f5b43ef5d02ad8b344133a530ecec1f29b"
            + "116f53df7bced6b22b7f22c3c38045ae22f41f630126f746e6708789939b8ff6"
            + "ae6cb8eb18e9834098187cd046cae61f0eee1bdf5459044329a3167451ea8d28"
            + "405a26c748b24f159ad93300506936cf22fd97cc80c64f696d810c73a1e0c959"
            + "08f47087713441fd63edabb64fccee4534758e00512015ef89af22f112a4f0b1"
            + "201b12e796d71b7a7536a0de2ccc22a06772a0151607cd87b3f74c9c502b53e8"
            + "740a8a2b894110fe86a5667380b9917d5ba76583facd8bfc706a733af91c85e5"
            + "44bfbef7293ad51ebdc2c17bf49241665db61aebca84be107914ebe8121dce38"
            + "605a725d2a4adfeeb1a29e17edd621c1b7593ee8cdbc44ac6c4ab6e2f805d23c"
        )
    }

    /// Expected 32-byte sealed body.
    private var expectedBody: Data {
        hex("2998be049fb54ca8f7830eb73b557844730bf0229d48159ac2d95e51eb02d8f3")
    }

    // MARK: - Key derivation

    func testPublicKeyDerivedFromSeedMatchesReference() throws {
        let identity = try HybridIdentity(seed: seed)
        XCTAssertEqual(identity.publicKey.count, 1216)
        XCTAssertEqual(identity.publicKey, expectedPublicKey)
    }

    func testDerivationIsDeterministic() throws {
        let a = try HybridIdentity(seed: seed)
        let b = try HybridIdentity(seed: seed)
        XCTAssertEqual(a.publicKey, b.publicKey)
    }

    // MARK: - Wrap / unwrap against the reference

    func testDeterministicWrapMatchesReferenceVector() throws {
        let recipient = try HybridRecipient(publicKey: expectedPublicKey)
        let stanza = try recipient.wrap(fileKey: fileKey, testRandom: testRandom)

        XCTAssertEqual(stanza.type, "mlkem768x25519")
        XCTAssertEqual(stanza.args.count, 1)
        XCTAssertEqual(try Stanza.base64Decode(stanza.args[0]), expectedEnc)
        XCTAssertEqual(stanza.body, expectedBody)
    }

    func testIdentityUnwrapsReferenceStanza() throws {
        let stanza = Stanza(
            type: "mlkem768x25519",
            args: [Stanza.base64NoPad(expectedEnc)],
            body: expectedBody
        )
        let recovered = try HybridIdentity(seed: seed).unwrap(stanza: stanza)
        XCTAssertEqual(recovered, fileKey)
    }

    func testWrapThenUnwrapRoundTrips() throws {
        let identity = try HybridIdentity.generate()
        let fk = Data((0..<16).map { UInt8($0) })
        let stanza = try identity.recipient().wrap(fileKey: fk)
        XCTAssertEqual(try identity.unwrap(stanza: stanza), fk)
    }

    // MARK: - Rejection

    func testUnwrapReturnsNilForForeignStanza() throws {
        let stanza = Stanza(
            type: "X25519",
            args: [Stanza.base64NoPad(Data(repeating: 0, count: 32))],
            body: Data(repeating: 0, count: 32)
        )
        XCTAssertNil(try HybridIdentity(seed: seed).unwrap(stanza: stanza))
    }

    func testUnwrapReturnsNilForAnotherIdentity() throws {
        let mine = try HybridIdentity.generate()
        let theirs = try HybridIdentity.generate()
        let stanza = try theirs.recipient().wrap(fileKey: fileKey)
        XCTAssertNil(try mine.unwrap(stanza: stanza))
    }

    func testUnwrapReturnsNilForTamperedBody() throws {
        var tampered = Array(expectedBody)
        tampered[0] ^= 1
        let stanza = Stanza(
            type: "mlkem768x25519",
            args: [Stanza.base64NoPad(expectedEnc)],
            body: Data(tampered)
        )
        XCTAssertNil(try HybridIdentity(seed: seed).unwrap(stanza: stanza))
    }

    // MARK: - Bech32 key strings
    //
    // An age1pq recipient runs to 1959 characters, well past BIP-0173's 90-char
    // limit. These would have been undecodable before the cap was raised.

    func testRecipientBech32RoundTrips() throws {
        let identity = try HybridIdentity(seed: seed)
        let encoded = try identity.recipient().ageRecipient

        XCTAssertTrue(encoded.hasPrefix("age1pq1"))
        XCTAssertEqual(encoded.count, 1959)
        XCTAssertEqual(
            hexString(SHA3.sha3_256(Data(encoded.utf8))),
            "ae64ad9ceb44cafc273fc5de5a18f803d6e4d442e047fb4cdcfe00034b29a810"
        )
        XCTAssertEqual(try HybridRecipient(ageRecipient: encoded).publicKey, identity.publicKey)
    }

    func testIdentityBech32RoundTrips() throws {
        let identity = try HybridIdentity(seed: seed)
        let encoded = identity.ageIdentityString
        XCTAssertEqual(encoded, "AGE-SECRET-KEY-PQ-1QQQSYQCYQ5RQWZQFPG9SCRGWPUGPZYSNZS23V9CCRYDPK8QARC0S5DYVQQ")
        XCTAssertEqual(try HybridIdentity(ageIdentity: encoded).seed, identity.seed)
    }

    func testBech32RejectsWrongHRP() throws {
        let x25519Recipient = X25519Identity.generate().ageRecipient
        XCTAssertThrowsError(try HybridRecipient(ageRecipient: x25519Recipient))
    }

    // MARK: - End to end through the age pipeline

    func testEndToEndThroughAgePipeline() throws {
        let identity = try HybridIdentity.generate()
        let plaintext = Data("hello post-quantum age\n".utf8)
        let ciphertext = try Age.encrypt(plaintext: plaintext, to: [try identity.recipient()])
        XCTAssertEqual(try Age.decrypt(ciphertext: ciphertext, identities: [identity]), plaintext)
    }

    func testEndToEndStreamingThroughAgePipeline() throws {
        let identity = try HybridIdentity.generate()
        let plaintext = Data(repeating: 0xAB, count: 200_000)

        let input = InputStream(data: plaintext)
        let output = OutputStream.toMemory()
        try Age.encryptStream(plaintext: input, to: [try identity.recipient()], into: output)
        output.close()
        let ciphertext = output.property(forKey: .dataWrittenToMemoryStreamKey) as? Data ?? Data()

        let back = InputStream(data: ciphertext)
        let plainOut = OutputStream.toMemory()
        try Age.decryptStream(ciphertext: back, identities: [identity], into: plainOut)
        plainOut.close()
        let recovered = plainOut.property(forKey: .dataWrittenToMemoryStreamKey) as? Data ?? Data()

        XCTAssertEqual(recovered, plaintext)
    }

    // MARK: - The post-quantum mixing rule
    //
    // A file readable by an X25519 key is only as quantum-safe as X25519, so age
    // refuses to mix a post-quantum recipient with a classical one rather than
    // silently downgrading the guarantee.

    func testPostQuantumRecipientCarriesLabel() throws {
        let recipient = try HybridIdentity.generate().recipient()
        XCTAssertEqual(recipient.labels, ["postquantum"])
    }

    func testMixingPostQuantumWithClassicalIsRejected() throws {
        let pq = try HybridIdentity.generate().recipient()
        let classical = X25519Identity.generate()
        let classicalRecipient = try X25519Recipient(publicKey: classical.publicKey)

        XCTAssertThrowsError(
            try Age.encrypt(plaintext: Data("nope".utf8), to: [pq, classicalRecipient])
        ) { error in
            XCTAssertEqual(error as? AgeError, .mismatchedRecipientLabels)
        }
    }

    func testTwoPostQuantumRecipientsAreAllowed() throws {
        let a = try HybridIdentity.generate()
        let b = try HybridIdentity.generate()
        let plaintext = Data("two post-quantum readers".utf8)

        let ciphertext = try Age.encrypt(
            plaintext: plaintext,
            to: [try a.recipient(), try b.recipient()]
        )
        XCTAssertEqual(try Age.decrypt(ciphertext: ciphertext, identities: [a]), plaintext)
        XCTAssertEqual(try Age.decrypt(ciphertext: ciphertext, identities: [b]), plaintext)
    }

    func testTwoClassicalRecipientsStillAllowed() throws {
        let a = X25519Identity.generate()
        let b = X25519Identity.generate()
        let plaintext = Data("unlabeled recipients still mix".utf8)

        let ciphertext = try Age.encrypt(
            plaintext: plaintext,
            to: [try X25519Recipient(publicKey: a.publicKey),
                 try X25519Recipient(publicKey: b.publicKey)]
        )
        XCTAssertEqual(try Age.decrypt(ciphertext: ciphertext, identities: [a]), plaintext)
    }
}
