//
//  MLKEM768.swift
//  AgePonyCore
//
//  ML-KEM-768 (FIPS 203, *final*) implemented from scratch.
//
//  Android delegates this to Bouncy Castle. Apple ships no ML-KEM reachable from
//  this deployment target, so iOS implements the lattice math directly: the NTT,
//  polynomial arithmetic, compression and byte encoding, K-PKE, and the ML-KEM
//  wrapper with implicit rejection.
//
//  Exposed surface is exactly what the MLKEM768-X25519 hybrid KEM needs:
//    - deterministic key generation from a 64-byte seed (d || z), so an age
//      identity seed reproduces the same keypair on every device,
//    - deterministic or random encapsulation,
//    - decapsulation.
//
//  FIPS 203 *final* matters here. The final standard domain-separates the key
//  generation seed as G(d || k), which the earlier IPD draft did not — the two
//  derive *different* keys from the same seed. This implements the final version,
//  pinned to reference vectors generated by filippo.io/hpke (the code age v1.3.0+
//  uses) in MLKEMTests / HybridTests.
//
//  Note on constant-time behaviour: this is a from-scratch implementation in
//  Swift and is not hardened against timing side channels. That matches the
//  threat model of the rest of AgePonyCore, where the attacker has the file, not
//  a timer on the device. It should not be reused where an adaptive attacker can
//  measure decapsulation.
//

import Foundation
import Security

public enum MLKEMError: Error, Equatable {
    case invalidSeedLength
    case invalidEncapsulationKeyLength
    case invalidDecapsulationKeyLength
    case invalidCiphertextLength
    case invalidMessageLength
}

public enum MLKEM768 {

    // MARK: - Parameters

    static let n = 256
    static let q: Int32 = 3329
    static let k = 3
    static let eta1 = 2
    static let eta2 = 2
    static let du = 10
    static let dv = 4

    /// ML-KEM key seed: d(32) || z(32).
    public static let seedSize = 64
    /// Encapsulation key: ByteEncode_12(t_hat)(1152) || rho(32).
    public static let encapsulationKeySize = 384 * k + 32      // 1184
    /// Decapsulation key: dk_PKE || ek || H(ek) || z.
    public static let decapsulationKeySize = 768 * k + 96      // 2400
    public static let ciphertextSize = 32 * (du * k + dv)      // 1088
    public static let sharedSecretSize = 32
    /// Encapsulation randomness.
    public static let messageSize = 32

    // MARK: - Hash / XOF helpers (FIPS 203 §4.1)

    @inline(__always) private static func H(_ b: Data) -> Data { SHA3.sha3_256(b) }
    @inline(__always) private static func G(_ b: Data) -> Data { SHA3.sha3_512(b) }
    @inline(__always) private static func J(_ b: Data) -> Data { SHA3.shake256(b, outputByteCount: 32) }

    @inline(__always)
    private static func PRF(_ eta: Int, _ s: Data, _ b: UInt8) -> [UInt8] {
        Array(SHA3.shake256(s + Data([b]), outputByteCount: 64 * eta))
    }

    @inline(__always)
    private static func XOF(_ rho: Data, _ i: UInt8, _ j: UInt8) -> KeccakSponge {
        SHA3.shake128Sponge(rho + Data([i, j]))
    }

    // MARK: - Zetas

    private static func bitRev7(_ x: Int) -> Int {
        var v = x
        var r = 0
        for _ in 0..<7 {
            r = (r << 1) | (v & 1)
            v >>= 1
        }
        return r
    }

    private static func powMod(_ base: Int, _ exp: Int, _ modulus: Int) -> Int32 {
        var result = 1
        var b = base % modulus
        var e = exp
        while e > 0 {
            if e & 1 == 1 { result = (result * b) % modulus }
            b = (b * b) % modulus
            e >>= 1
        }
        return Int32(result)
    }

    /// zeta^BitRev7(i) mod q, for the NTT butterflies.
    static let zetas: [Int32] = (0..<128).map { powMod(17, bitRev7($0), Int(q)) }

    /// zeta^(2*BitRev7(i)+1) mod q, for the degree-1 base-case multiply.
    static let gammas: [Int32] = (0..<128).map { powMod(17, 2 * bitRev7($0) + 1, Int(q)) }

    // MARK: - Polynomial arithmetic
    //
    // A polynomial is 256 coefficients mod q, held as Int32.

    typealias Poly = [Int32]

    @inline(__always)
    static func mod(_ x: Int32) -> Int32 {
        let r = x % q
        return r < 0 ? r + q : r
    }

    static func polyAdd(_ a: Poly, _ b: Poly) -> Poly {
        var out = Poly(repeating: 0, count: n)
        for i in 0..<n { out[i] = mod(a[i] + b[i]) }
        return out
    }

    static func polySub(_ a: Poly, _ b: Poly) -> Poly {
        var out = Poly(repeating: 0, count: n)
        for i in 0..<n { out[i] = mod(a[i] - b[i]) }
        return out
    }

    /// FIPS 203 Algorithm 9: Cooley-Tukey, natural order in, bit-reversed out.
    static func ntt(_ f: Poly) -> Poly {
        var f = f
        var i = 1
        var length = 128
        while length >= 2 {
            var start = 0
            while start < 256 {
                let zeta = zetas[i]
                i += 1
                for j in start..<(start + length) {
                    let t = mod(zeta * f[j + length])
                    f[j + length] = mod(f[j] - t)
                    f[j] = mod(f[j] + t)
                }
                start += 2 * length
            }
            length /= 2
        }
        return f
    }

    /// FIPS 203 Algorithm 10: Gentleman-Sande, then scale by 128^-1 = 3303 mod q.
    static func nttInverse(_ f: Poly) -> Poly {
        var f = f
        var i = 127
        var length = 2
        while length <= 128 {
            var start = 0
            while start < 256 {
                let zeta = zetas[i]
                i -= 1
                for j in start..<(start + length) {
                    let t = f[j]
                    f[j] = mod(t + f[j + length])
                    f[j + length] = mod(zeta * mod(f[j + length] - t))
                }
                start += 2 * length
            }
            length *= 2
        }
        for idx in 0..<n { f[idx] = mod(f[idx] * 3303) }
        return f
    }

    /// FIPS 203 Algorithm 11: 128 independent degree-1 products mod (X^2 - gamma).
    static func nttMultiply(_ a: Poly, _ b: Poly) -> Poly {
        var out = Poly(repeating: 0, count: n)
        for i in 0..<128 {
            let a0 = a[2 * i], a1 = a[2 * i + 1]
            let b0 = b[2 * i], b1 = b[2 * i + 1]
            let g = gammas[i]
            out[2 * i] = mod(mod(a0 * b0) + mod(mod(a1 * b1) * g))
            out[2 * i + 1] = mod(mod(a0 * b1) + mod(a1 * b0))
        }
        return out
    }

    // MARK: - Sampling

    /// FIPS 203 Algorithm 7: rejection-sample a polynomial already in the NTT domain.
    ///
    /// Rejection sampling cannot bound its input in advance, so this pulls from an
    /// incremental sponge rather than a pre-squeezed buffer.
    static func sampleNTT(_ xof: inout KeccakSponge) -> Poly {
        var a = Poly()
        a.reserveCapacity(n)
        while a.count < n {
            let chunk = Array(xof.squeeze(3))
            let b0 = Int32(chunk[0]), b1 = Int32(chunk[1]), b2 = Int32(chunk[2])
            let d1 = b0 + 256 * (b1 % 16)
            let d2 = (b1 / 16) + 16 * b2
            if d1 < q { a.append(d1) }
            if d2 < q && a.count < n { a.append(d2) }
        }
        return a
    }

    /// FIPS 203 Algorithm 8: centered binomial distribution from 64*eta bytes.
    static func samplePolyCBD(_ eta: Int, _ bytes: [UInt8]) -> Poly {
        var bits = [UInt8](repeating: 0, count: bytes.count * 8)
        for (i, byte) in bytes.enumerated() {
            for b in 0..<8 { bits[8 * i + b] = (byte >> b) & 1 }
        }
        var f = Poly(repeating: 0, count: n)
        for i in 0..<n {
            var x: Int32 = 0
            var y: Int32 = 0
            for j in 0..<eta {
                x += Int32(bits[2 * i * eta + j])
                y += Int32(bits[2 * i * eta + eta + j])
            }
            f[i] = mod(x - y)
        }
        return f
    }

    // MARK: - Compression and encoding

    @inline(__always)
    static func compress(_ d: Int, _ x: Int32) -> Int32 {
        // round(2^d / q * x) mod 2^d, rounding halves up.
        let numerator = (Int64(x) << Int64(d)) + Int64(q / 2)
        return Int32((numerator / Int64(q)) % (Int64(1) << Int64(d)))
    }

    @inline(__always)
    static func decompress(_ d: Int, _ y: Int32) -> Int32 {
        Int32((Int64(y) * Int64(q) + (Int64(1) << Int64(d - 1))) >> Int64(d))
    }

    /// Pack 256 d-bit values little-endian into 32*d bytes.
    static func byteEncode(_ d: Int, _ f: Poly) -> [UInt8] {
        var out = [UInt8](repeating: 0, count: 32 * d)
        var acc: UInt32 = 0
        var bits = 0
        var idx = 0
        let mask: UInt32 = d == 32 ? .max : (UInt32(1) << UInt32(d)) - 1
        for coeff in f {
            acc |= (UInt32(bitPattern: coeff) & mask) << UInt32(bits)
            bits += d
            while bits >= 8 {
                out[idx] = UInt8(truncatingIfNeeded: acc)
                idx += 1
                acc >>= 8
                bits -= 8
            }
        }
        return out
    }

    static func byteDecode(_ d: Int, _ data: [UInt8]) -> Poly {
        var f = Poly(repeating: 0, count: n)
        var acc: UInt32 = 0
        var bits = 0
        var idx = 0
        let mask: UInt32 = (UInt32(1) << UInt32(d)) - 1
        for i in 0..<n {
            while bits < d {
                acc |= UInt32(data[idx]) << UInt32(bits)
                idx += 1
                bits += 8
            }
            let value = Int32(acc & mask)
            // d == 12 carries raw coefficients, which must be reduced mod q.
            f[i] = d == 12 ? mod(value) : value
            acc >>= UInt32(d)
            bits -= d
        }
        return f
    }

    static func encodeVector(_ d: Int, _ vec: [Poly]) -> [UInt8] {
        var out = [UInt8]()
        out.reserveCapacity(32 * d * vec.count)
        for p in vec { out.append(contentsOf: byteEncode(d, p)) }
        return out
    }

    static func decodeVector(_ d: Int, _ data: [UInt8], count: Int) -> [Poly] {
        let step = 32 * d
        return (0..<count).map { byteDecode(d, Array(data[($0 * step)..<(($0 + 1) * step)])) }
    }

    // MARK: - K-PKE

    /// A_hat[i][j] = SampleNTT(XOF(rho, j, i)) per FIPS 203.
    private static func buildMatrix(rho: Data) -> [[Poly]] {
        var a = [[Poly]]()
        a.reserveCapacity(k)
        for i in 0..<k {
            var row = [Poly]()
            row.reserveCapacity(k)
            for j in 0..<k {
                var xof = XOF(rho, UInt8(j), UInt8(i))
                row.append(sampleNTT(&xof))
            }
            a.append(row)
        }
        return a
    }

    static func kpkeKeyGen(d: Data) -> (ek: [UInt8], dk: [UInt8]) {
        // FIPS 203 final: the seed is domain-separated by k.
        let g = G(d + Data([UInt8(k)]))
        let rho = g.prefix(32)
        let sigma = Data(g.suffix(32))
        let aHat = buildMatrix(rho: Data(rho))

        var counter: UInt8 = 0
        var s = [Poly]()
        for _ in 0..<k {
            s.append(samplePolyCBD(eta1, PRF(eta1, sigma, counter)))
            counter += 1
        }
        var e = [Poly]()
        for _ in 0..<k {
            e.append(samplePolyCBD(eta1, PRF(eta1, sigma, counter)))
            counter += 1
        }

        let sHat = s.map { ntt($0) }
        let eHat = e.map { ntt($0) }

        var tHat = [Poly]()
        for i in 0..<k {
            var acc = Poly(repeating: 0, count: n)
            for j in 0..<k {
                acc = polyAdd(acc, nttMultiply(aHat[i][j], sHat[j]))
            }
            tHat.append(polyAdd(acc, eHat[i]))
        }

        let ek = encodeVector(12, tHat) + Array(rho)
        let dk = encodeVector(12, sHat)
        return (ek, dk)
    }

    static func kpkeEncrypt(ek: [UInt8], message: [UInt8], randomness r: Data) -> [UInt8] {
        let tHat = decodeVector(12, Array(ek[0..<(384 * k)]), count: k)
        let rho = Data(ek[(384 * k)..<(384 * k + 32)])
        let aHat = buildMatrix(rho: rho)

        var counter: UInt8 = 0
        var y = [Poly]()
        for _ in 0..<k {
            y.append(samplePolyCBD(eta1, PRF(eta1, r, counter)))
            counter += 1
        }
        var e1 = [Poly]()
        for _ in 0..<k {
            e1.append(samplePolyCBD(eta2, PRF(eta2, r, counter)))
            counter += 1
        }
        let e2 = samplePolyCBD(eta2, PRF(eta2, r, counter))

        let yHat = y.map { ntt($0) }

        // u = NTT^-1(A_hat^T . y_hat) + e1
        var u = [Poly]()
        for i in 0..<k {
            var acc = Poly(repeating: 0, count: n)
            for j in 0..<k {
                acc = polyAdd(acc, nttMultiply(aHat[j][i], yHat[j]))
            }
            u.append(polyAdd(nttInverse(acc), e1[i]))
        }

        let mu = byteDecode(1, message).map { decompress(1, $0) }

        var acc = Poly(repeating: 0, count: n)
        for i in 0..<k {
            acc = polyAdd(acc, nttMultiply(tHat[i], yHat[i]))
        }
        let v = polyAdd(polyAdd(nttInverse(acc), e2), mu)

        let c1 = encodeVector(du, u.map { p in p.map { compress(du, $0) } })
        let c2 = byteEncode(dv, v.map { compress(dv, $0) })
        return c1 + c2
    }

    static func kpkeDecrypt(dk: [UInt8], ciphertext c: [UInt8]) -> [UInt8] {
        let split = 32 * du * k
        let c1 = Array(c[0..<split])
        let c2 = Array(c[split...])

        let u = decodeVector(du, c1, count: k).map { p in p.map { decompress(du, $0) } }
        let v = byteDecode(dv, c2).map { decompress(dv, $0) }
        let sHat = decodeVector(12, dk, count: k)

        var acc = Poly(repeating: 0, count: n)
        for i in 0..<k {
            acc = polyAdd(acc, nttMultiply(sHat[i], ntt(u[i])))
        }
        let w = polySub(v, nttInverse(acc))
        return byteEncode(1, w.map { compress(1, $0) })
    }

    // MARK: - ML-KEM

    /// A generated keypair: the encapsulation key and the decapsulation key.
    public struct KeyPair {
        public let encapsulationKey: Data
        public let decapsulationKey: Data
    }

    /// FIPS 203 ML-KEM.KeyGen_internal(d, z).
    static func keyGenInternal(d: Data, z: Data) -> KeyPair {
        let (ek, dkPKE) = kpkeKeyGen(d: d)
        let ekData = Data(ek)
        let dk = Data(dkPKE) + ekData + H(ekData) + z
        return KeyPair(encapsulationKey: ekData, decapsulationKey: dk)
    }

    /// Deterministic key generation from a 64-byte seed `d || z`.
    ///
    /// A fixed seed reproduces the reference keypair exactly, which is what lets an
    /// age identity seed regenerate the same key on every device.
    public static func keyPairFromSeed(_ seed: Data) throws -> KeyPair {
        guard seed.count == seedSize else { throw MLKEMError.invalidSeedLength }
        let d = Data(seed.prefix(32))
        let z = Data(seed.suffix(32))
        return keyGenInternal(d: d, z: z)
    }

    /// Encapsulate to `encapsulationKey`, returning the shared secret and ciphertext.
    ///
    /// `message` supplies the 32 bytes of encapsulation randomness. When nil, fresh
    /// random bytes are used; supplying it makes the operation deterministic for
    /// known-answer tests.
    public static func encapsulate(
        encapsulationKey ek: Data,
        message: Data? = nil
    ) throws -> (sharedSecret: Data, ciphertext: Data) {
        guard ek.count == encapsulationKeySize else { throw MLKEMError.invalidEncapsulationKeyLength }
        let m: Data
        if let message {
            guard message.count == messageSize else { throw MLKEMError.invalidMessageLength }
            m = message
        } else {
            m = randomBytes(messageSize)
        }
        let g = G(m + H(ek))
        let sharedSecret = Data(g.prefix(32))
        let r = Data(g.suffix(32))
        let c = kpkeEncrypt(ek: Array(ek), message: Array(m), randomness: r)
        return (sharedSecret, Data(c))
    }

    /// Decapsulate `ciphertext`, returning the 32-byte shared secret.
    ///
    /// On a ciphertext that does not re-encrypt to itself, FIPS 203 implicit
    /// rejection returns a deterministic pseudorandom secret rather than failing,
    /// so a caller learns nothing about *why* it did not work.
    public static func decapsulate(
        decapsulationKey dk: Data,
        ciphertext c: Data
    ) throws -> Data {
        guard dk.count == decapsulationKeySize else { throw MLKEMError.invalidDecapsulationKeyLength }
        guard c.count == ciphertextSize else { throw MLKEMError.invalidCiphertextLength }

        let dkBytes = Array(dk)
        let dkPKE = Array(dkBytes[0..<(384 * k)])
        let ekPKE = Array(dkBytes[(384 * k)..<(768 * k + 32)])
        let h = Data(dkBytes[(768 * k + 32)..<(768 * k + 64)])
        let z = Data(dkBytes[(768 * k + 64)..<(768 * k + 96)])

        let mPrime = kpkeDecrypt(dk: dkPKE, ciphertext: Array(c))
        let g = G(Data(mPrime) + h)
        let sharedPrime = Data(g.prefix(32))
        let rPrime = Data(g.suffix(32))
        let sharedBar = J(z + c)
        let cPrime = kpkeEncrypt(ek: ekPKE, message: mPrime, randomness: rPrime)

        return constantTimeEquals(cPrime, Array(c)) ? sharedPrime : sharedBar
    }

    // MARK: - Helpers

    @inline(never)
    private static func constantTimeEquals(_ a: [UInt8], _ b: [UInt8]) -> Bool {
        guard a.count == b.count else { return false }
        var diff: UInt8 = 0
        for i in 0..<a.count { diff |= a[i] ^ b[i] }
        return diff == 0
    }

    /// Cryptographically secure random bytes.
    ///
    /// Uses `SecRandomCopyBytes` rather than `UInt8.random`. Both are CSPRNG-backed on
    /// Apple platforms, but ML-KEM encapsulation randomness is key material and the
    /// guarantee is worth making explicit at the point of use.
    static func randomBytes(_ count: Int) -> Data {
        var bytes = [UInt8](repeating: 0, count: count)
        let status = SecRandomCopyBytes(kSecRandomDefault, count, &bytes)
        guard status == errSecSuccess else {
            // SecRandomCopyBytes does not fail in practice on a healthy system; if it
            // ever does, failing loudly beats silently producing predictable key material.
            fatalError("SecRandomCopyBytes failed with status \(status)")
        }
        return Data(bytes)
    }
}
